### ISSUE TITLE
CaptureFromCamera360 Memory leak on iOS

### ISSUE THREAD

**Issue by LightGather** [RenderHeads/UnityPlugin-AVProMovieCapture#164]
**Describe the bug**
When I repeatedly captured 360 videos, the memory was accumulated. (About 50 Mega bytes for a capture)
This issue can be reproduced easily by building the "Demo 04-360 Capture" scene(included in the MovieCapture package) and running it on a iPhone.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.31f1 
 - AVPro Movie Capture version: 4.7.9 
 - Operating system version: iOS 15.4.1
 - Capture component used: CaptureFromCamera360
 - Capture settings (resolution, frame-rate, codec): 2560X1440, 30, H264

**To Reproduce**
1. Open the Demo04-360 Capture scene in Assets/Plugins/RenderHeads/AVProMovieCapture/Demos/Scenes
3. Build and run on iPhone 
4. Click "Start Render"
5. Wait for the above capture operation to finish. Repeat - Click "Start render".
6. Watch Xcode memory profiler

**Screenshots**
<img width="966" alt="memory_profile" src="https://user-images.githubusercontent.com/2079446/162900499-eb634353-9924-4de2-92b8-6b8003365ea3.png">

**Comment by LightGather** [comment]
If RH are dealing with this issue, could you please let me know the status? I really want to apply this to our app, so I hope this problem gets resolved.

**Comment by MorrisRH** [comment]
This issue is now fixed and will be available in the next release.

**Comment by LightGather** [comment]
I'm really glad this issue has been fixed. thanks!
When do you think the next release will be?

**Comment by AndrewRH** [comment]
@LightGather  should be today if all goes well

**Comment by LightGather** [comment]
There seems to be an issue still in 4.7.10. Please see the video I attached. When I first started recording, the memory was about 720 megabytes, but after repeating it a few times, it goes up to about 850 megabytes. As I said in the original text, I created an empty project and built and ran your 360 demo.
https://user-images.githubusercontent.com/2079446/165249235-26443b75-00ed-42f1-b8cb-2752051f4196.mp4

**Comment by MorrisRH** [comment]
Could you try using Instruments.app instead? The reporting in Xcode is a bit skewed due to logging being captured.
Would also be really handy if you could send on the logging output from Xcode.

**Comment by MorrisRH** [comment]
Thanks for the log output, it's given me some clues...

**Comment by MorrisRH** [comment]
Hopefully I've got it this time... a fix will be in the next release

**Comment by LightGather** [comment]
Thanks for fixing the issue so quickly. When a new version is released, I'll test it asap.

**Comment by AndrewRH** [comment]
AVPro Movie Capture 4.7.11 has been released and includes a fix for this issue.  Please let us know whether this resolves it for you.

**Comment by LightGather** [comment]
I just installed the new version and tested it, and there is no problem even if I repeat capture more than 10 times. I think it's completely resolved. Thank you so much!

**Comment by Chris-RH** [comment]
Great news, thank you for your feedback :)
